### ISSUE TITLE
Tests fail on MRI 2.2

### ISSUE THREAD

**Issue by mpapis** [rvm/gem-empty#6]
https://travis-ci.org/rvm/gem-empty/jobs/59320309

**Comment by mpapis** [comment]
@anfleene any chance you could look also into this one? btw. would you like to get into the RVM team? - drop me an email if yes.

**Comment by anfleene** [comment]
@mpapis Yeah. I'll try to take a look at that. I noticed it the first time I ran the tests. I think we might have to pick a different gem to test. Ruby 2.2 seems to have changed how it manages it's rake install. 

I'll send you an email

**Comment by mpapis** [comment]
ah right, some gems became default in `2.2` - might be just matter of reorganizing tests to account for that
